import shutil

# yt-dlp needs a JavaScript runtime to solve YouTube's signature challenges.
# Only deno is enabled by default, so we enable whichever one is installed.
JS_RUNTIMES = ("deno", "node", "bun", "quickjs")

# The client yt-dlp falls back to by default (android_vr) hands out media URLs
# that YouTube then refuses with HTTP 403 past the first few hundred KB, which
# is what kills a real download. The embedded-web client hands out working
# ones, so ask for it first and keep the others as fallbacks.
PLAYER_CLIENTS = ["web_embedded", "tv_simply", "default"]

# Fetch in ranged chunks rather than one long-lived request, so a stalled or
# rejected chunk can be retried on its own.
HTTP_CHUNK_SIZE = 10 * 1024 * 1024


def _available_js_runtimes():
    return {name: {} for name in JS_RUNTIMES if shutil.which(name)}


def build_ydl_opts(outtmpl):
    """yt-dlp options for grabbing the audio of a single track.

    We only ever feed audio to Shazam, so asking for a video stream would mean
    downloading gigabytes for nothing. `noplaylist` keeps a
    `watch?v=...&list=RD...` mix URL from expanding into the whole
    autogenerated playlist.
    """
    runtimes = _available_js_runtimes()
    if not runtimes:
        print(
            "WARNING: no JavaScript runtime found (deno/node/bun/quickjs). "
            "YouTube extraction without one is deprecated and some formats "
            "will be missing - see https://github.com/yt-dlp/yt-dlp/wiki/EJS"
        )

    return {
        "outtmpl": outtmpl,
        "format": "bestaudio/best",
        "noplaylist": True,
        "js_runtimes": runtimes,
        "extractor_args": {"youtube": {"player_client": PLAYER_CLIENTS}},
        "http_chunk_size": HTTP_CHUNK_SIZE,
        "retries": 10,
        "fragment_retries": 10,
        "extractor_retries": 3,
    }
