name: Service tests

on:
  push:
    branches: [ "master", "dev"]
  pull_request:
    branches: [ "master", "dev"]
env:
  ENV: TEST
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r server/requirements.txt
          pip install -r server/tests/requirements.txt
      - name: Test with pytest
        run: |
          python -m pytest
